### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by siena-italy**
lovely new quotes

### CODE REVIEW

**Comment by siena-italy** [comment]
MERGE PULL REQUEST

**Comment by KazMalhotra** [comment]
You need commas in the array

**Comment by siena-italy** [comment]
what array lol

**Comment by KazMalhotra** [comment]
stevequotes

**Comment by KazMalhotra** [comment]
```
var stevequotes = [
  "Plug in your chromebook -Steven Michael Pape, 2019",
  "If you keep the commons clean, maybe you can eat at assemblies -Steven Michael Pape, 2019",
  "Is that a phone is your pocket? -Steven Michael Pape, 2019",
  "I'll bring donuts for c&c -Steven Michael Pape, 2019",
  "My name is Dr. Roboto -Steven Michael Pape to some random 6th grader",
  "I wish there was something I could do -Steven Michael Pape when asked to do literally anything",
  "I don't make up the rules, I just enforce them -Steven Michael Pape, making up the rules",
  "Please put your chromebooks in the correct slot -Steve Pape, 2019",
  "Hello, have you plugged in your chromebook? -Steve Pape, 2019",
  "This is the third time you've left your chromebook out... should we brainstorm a plan to fix that? -Steve Pape, 2019",
  "Your chromebook is in my office. -Steve Pape, 2019",
  "Did you plug in your chromebook? -Steve Pape, 2019",
  "What is that on your other tab? -Steve Pape, 2019",
  "We have GREAT news! *pauses dramatically*... Everyone's chromebook was plugged in! -Steve Pape, 2020",
  "Who's Steve? - Steven Michael Pape pretending to be Dr. Roboto to any sixth grader."
]
```

**Comment by KazMalhotra** [comment]
please create a new pr

**Comment by KazMalhotra** [comment]
you have the array like this:
```
  "What is that on your other tab? -Steve Pape, 2019",
  "We have GREAT news! *pauses dramatically*... Everyone's chromebook was plugged in! -Steve Pape, 2020",
  "Who's Steve? - Steven Michael Pape pretending to be Dr. Roboto to any sixth grader."
  "Come see me in my office. - Steven Michael Pape when he has (stolen) your chromebook."
  "Beards are cool!"
]
```
where it should be like this:
```
  "What is that on your other tab? -Steve Pape, 2019",
  "We have GREAT news! *pauses dramatically*... Everyone's chromebook was plugged in! -Steve Pape, 2020",
  "Who's Steve? - Steven Michael Pape pretending to be Dr. Roboto to any sixth grader.",
  "Come see me in my office. - Steven Michael Pape when he has (stolen) your chromebook.",
  "Beards are cool!"
]
```
note the commas.
If you have questions, see https://www.w3schools.com/js/js_arrays.asp.

**Comment by KazMalhotra** [comment]
please open a new pr

**Comment by siena-italy** [comment]
uhhh why dont i just fill out your little quotey forms

**Pull request merged**
